### ISSUE TITLE
@2x images not outputting when using 'theme//' stream

### ISSUE THREAD

**Issue by apotropaic** [getgrav/grav#1600] opened 2017-08-05 01:09 UTC
On a fresh install these steps should allow you to reproduce this error:

1. In the antimatter theme, duplicate `images/logo.png` and call it `logonew@2x.png`
2. In the `default.html.twig` template output the image:
```
{% extends 'partials/base.html.twig' %}

{% block content %}
	 {{ media["theme://images/newlogo.png"].html() }} 
	 {{ page.content }} 
{% endblock %}

```
3. Load home page, no images show up. 
4. Change template code to output `logo.png` instead of `newlogo.png`
5 Reload home page and the logo images will output, since it is just a 1x/normal image

On a side note, if you move the same image `logonew@2x.png` into the `01. Home` page folder and then in your `default.html.twig` change the media output to: `page.media["newlogo.png"].html()` it ouputs as expected with the new images the grav creates, a 2x png and 1x png.

**Comment by rhukster** [comment] 2017-08-05 16:00
Does sound like a legit bug.  We'll look into it.  Cheers.

**Comment by rhukster** [comment] 2017-08-11 21:13
I had a look into this, and the short answer is that it's not something that is easily fixed.

Basically, Media functionality was intended to be used for pages only.  When a page is intialized, all the valid media types are iterated over and part of this process check for files such as `myimage@2x.jpg` that are in the `@2x` format.  If they are found, then they are intstantiated with 'alternative' references for the `@1x` sizes etc, the then 'prettyname' is set to `myimage.jpg` so they can be retrieved via the media object with both @2x and @1x formats available.

The stream reference approach simply looks for a file directly matching the stream provided. If it's found, a media object is created on the fly and you are able to use media functions for it.  However, if you have a stream for `user://media/myimage.jpg` it won't find it because the file is actually `user/media/myimage@2x.jpg`.  There's really no great way to know what the original file is called because we have no iterated over the files (as we do in pages), we are simply looking for a specific file using magic offsets.

As things stand the best way to handle this is to have a plugin that creates a new media object that points to the folder you want to use. This would then use the same process as pages, and iterate over the media files in the path provided. Then you could assign this media object to a twig variable and get the full functionality you wold in pages.  However, as this would be called manually each time, you would have to accept the performance penalties, or add your own caching (similar to how each page caches its media object)/

**Closed by rhukster** 2017-08-11 21:13 UTC
Labels: bug

**Comment by mahagr** [comment] 2017-08-14 06:55
I think you can still use meta-file to define different media sizes?
