### ISSUE TITLE
Disabling translations causes internal server error

### ISSUE THREAD

**Issue by tjforsythe** [getgrav/grav#478] opened 2015-11-25 17:14 UTC
I have languages enabled and translation turned on.  In the admin panel when I disable translations and click save, it displays an internal server error box.  When I reload the admin panel I get an error.

500
Server Error
Sorry, something went terribly wrong!
E_ERROR - Call to a member function get() on a non-object
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

The log shows:

[2015-11-25 09:05:07] grav.CRITICAL: Call to a member function get() on a non-object - Trace: #0 /home4/gigatree/public_html/s2/vendor/filp/whoops/src/Whoops/Run.php(357): Whoops\Run->handleError(1, 'Call to a membe...', '/home4/gigatree...', 433) #1 [internal function]: Whoops\Run->handleShutdown() #2 {main} [] []

I've attached the good (before) and bad (after) yaml files.  The only diff is the 
languages: translations: true/false.

If i set it back to false.  The admin panel loads fine.  If i set it to true, I get the error.

[user.config..system.yaml.good.txt](https://github.com/getgrav/grav/files/44121/user.config.system.yaml.good.txt)
[user.configsystem.yam.bad.txt](https://github.com/getgrav/grav/files/44122/user.configsystem.yam.bad.txt)

**Comment by flaviocopes** [comment] 2015-11-25 17:39
Can you turn on error reporting (system.errors.display) to see a more detailed stack trace of the error? I cannot reproduce the problem even when adding your bad system.yaml

**Comment by tjforsythe** [comment] 2015-11-25 17:47
okay what would you like me to send you

**Comment by flaviocopes** [comment] 2015-11-25 17:50
Just turn on error reporting and post the error / screenshot of the error details

**Comment by tjforsythe** [comment] 2015-11-25 18:10
![snap8](https://cloud.githubusercontent.com/assets/13544904/11405458/c4b47922-935c-11e5-9e42-64da337d44be.png)

**Comment by flaviocopes** [comment] 2015-11-25 18:27
Ok I see I recreated it on a skeleton with the current Grav version. It's already fixed in the repository, will be fixed in the next Grav update!

**Closed by flaviocopes** 2015-11-25 18:27 UTC

**Comment by tjforsythe** [comment] 2015-11-25 18:28
great, thanks
