### ISSUE TITLE
Error while updating from 1.6.10 to 1.7.5

### ISSUE THREAD

**Issue by studioem** [getgrav/grav#3222] opened 2021-02-12 12:19 UTC
<img width="1020" alt="Capture d’écran 2021-02-12 à 13 01 59" src="https://user-images.githubusercontent.com/59135955/107771891-c1643500-6d3b-11eb-86f5-a57f43c9e240.png">
Hi there, 
I'm trying to update from 1.6.10 to 1.7.5. Everything goes well with the website itself but the admin panel now shows "Plugin.admin.pages" instead of "pages", "plugin.admin.plugins" insted of "plugins" and so one for every buttons on the admin panel.

Do you know a solution to make it back to a normal display ?

Thank you!

**Comment by pamtbaau** [comment] 2021-02-12 14:24
Looks similar to an issue mentioned on [discourse](https://discourse.getgrav.org/t/weird-admin-backend-after-grav-update-to-1-7-5/15252).

Issue was fixed by re-enabling translations in the 'languages' section in file '/user/config/system.yaml', or via Admin.
```
languages:
  translations: true
```

Since this is not the first time the issue is mentioned, there might be something going wrong while upgrading.

**Comment by studioem** [comment] 2021-02-12 14:31
thank you for this tip! It partly fixes the problem, however there is still some button with the display issue.

<img width="1791" alt="Capture d’écran 2021-02-12 à 15 29 01" src="https://user-images.githubusercontent.com/59135955/107780658-430d9000-6d47-11eb-9ddf-b665d9ada4aa.png">

**Comment by studioem** [comment] 2021-02-12 14:33
Thank your for the tip! It fixed the problem on my side.
I leave the issue open as I'm not the only one having it.

**Closed** 2021-02-27 04:01 UTC
