### ISSUE TITLE
Add page button does nothing on Edge

### ISSUE THREAD

**Issue by MathiasMagnus** [getgrav/grav#1470] opened 2017-05-12 11:40 UTC
If I try to add a new page, I fill out the pop-up form (providing root page, visibility and what not), but clicking the Continue button does nothing. Edge with Creators Update.

Version numbers (obtained from Settings panel)
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by flaviocopes** [comment] 2017-05-12 13:46
Hmm, duplicate of https://github.com/getgrav/grav-plugin-admin/issues/1061

I tested Edge on BrowserStack and it seems to work fine. Do you see any javascript error in the browser developer console?

**Comment by rhukster** [comment] 2017-05-17 17:16
What other plugins do you have installed?

**Closed** 2020-12-10 14:50 UTC
Labels: cannot replicate
