### ISSUE TITLE
Media MIME types being checked too strictly

### ISSUE THREAD

**Issue by brendanpetty** [getgrav/grav#3385] opened 2021-06-21 06:56 UTC
Browsers are not entirely consistent with the MIME type they declare a file as. This is stopping uploads into the media of a page through the admin.

For an mp3 file, the browser is sending "audio/mpeg" but GRAV expects "audio/mp3". In Grav\Common\Media\Traits\MediaUploadTrait around line 188 there is a test that both these need to match.

This test needs to have more grace, or be able to be disabled somewhere, or an extra warning but allow the upload, etc. Currently unusable.

**Comment by mahagr** [comment] 2021-06-21 07:41
@rhukster You know better how/where the mime types are being handled.

**Comment by mahagr** [comment] 2021-08-13 17:07
Duplicate of #3422

**Closed by mahagr** 2021-08-13 17:07 UTC
