### ISSUE TITLE
Duplicate Content on /home

### ISSUE THREAD

**Issue by henk23** [getgrav/grav#2641] opened 2019-08-20 15:55 UTC
Irrespective of the `home.hide_in_urls` setting in system.yaml: When I open `my.site/home` or `my.site/`, the content is identical. Isn't that supposed to be bad for SEO?
Is there a way to let `my.site/` load `pages/01.home` and `my.site/home` display a 404 page?

**Comment by ulab** [comment] 2019-08-21 07:06
This does not affect SEO at all, since your template should include a canonical URL meta tag like `<link rel="canonical" href="https://example.com">` telling search engines the main / preferred URL for the page.

My site also does not create links to `/home` in the navigation or somewhere else which would make crawlers find the alternative page URL, unless someone manually tells them or links to it. 

As fars as I understand, `Hide home route in URLs` only affects child pages you create with `/home` as parent, while you create other pages below the root `/` usually?

**Comment by mahagr** [comment] 2019-09-17 07:55
Yes, if you place items under /home (for the menu navigation), they will use that route unless the setting is being used.

**Comment by replayshot** [comment] 2020-09-23 10:32
This seems to be a bit related, but in my case /home is the /blog. 

For some reason, I can access a blog page from 2 different URLs.
a) domain.com/blog/post-1
b) domain.com/post-1

I've set the /blog to be my homepage in Configuration. 
home:
  alias: /blog
  hide_in_urls: true

So, I'd expect the path: a) from my example above to give me 404 or automatically redirect to the URL b). 

Is this a bug or expected behavior?
I have v 1.7.0-rc16 and Admin 1.10.0-rc.16 installed. 

I've another older installation v1.6.27 - Admin v1.9.15 and there it seems to work as I'd expect only b) works and a) shows 404

Btw, in terms of SEO, yes canonicals help of course, but it is never a good practice to have duplicates.

**Comment by mahagr** [comment] 2021-03-31 16:49
This has been fixed in the latest versions but needs some settings to be changed. See `system.pages.redirect_default_route` setting.

**Closed by mahagr** 2021-03-31 16:49 UTC
Labels: question
