### ISSUE TITLE
Page parent automatically changes to root when editing through plugin admin

### ISSUE THREAD

**Issue by matt-j-m** [getgrav/grav#2362] opened 2019-02-05 00:03 UTC
Sounds similar to issue #1425 however I am experiencing on latest version Grav v1.5.7 - Admin v1.8.16.

It appears as though any subdirectories not containing a .md file are begin excluded from the Parent list, thus causing any subdirectories below them to inadvertently be moved to the root directory on page save.

For example, say I have a directory in pages root such as /somedir. /somedir contains multiple subdirectories, **but no .md file**, as I don't want http://myurl.com/somedir to be a routable url. When I go to edit a page at /somedir/anotherdir/mypage.md, prior to latest version, the Advanced tab > Settings > Parent value would display "—-▸ (somedir) Somedir". As of latest version, this value now defaults to "/ (root)", and **"—-▸ (somedir) Somedir" is no longer available as an option**. When the page is saved, it is inevitably moved to root.

**Comment by matt-j-m** [comment] 2019-02-05 00:12
Current workaround is to create error.md in the previously empty subdirectory with the contents:

````
---
title: Page not Found
http_response_code: 404
---
````

**Comment by rhukster** [comment] 2019-02-05 23:16
Did you try Grav 1.6? Pretty sure this is fixed there.

**Comment by rhukster** [comment] 2019-02-05 23:20
Confirmed.  Saving a page with an empty parent folder, saves just fine in Grav 1.6 with Admin 1.9.

**Comment by matt-j-m** [comment] 2019-02-06 03:35
Thank you @rhukster Looking forward to 1.6 release

**Comment by drnasin** [comment] 2019-02-11 13:42
I'm having the same issue - Grav v1.5.8 - Admin v1.8.17

**Comment by drnasin** [comment] 2019-02-12 09:31
@rhukster huh ok this is a bit more serious. I updated locally 4 of my Grav instances just to test it before live update and after the update they all  have this bug. I managed to found the culprit:

https://github.com/getgrav/grav-plugin-admin/pull/1571/commits/3c888b6d226bedacca4f07d60af83d9a970b3678

after reverting this everything works ok. Parent is shown ok...
Can anyone take a look at this.

**Comment by rhukster** [comment] 2019-02-12 10:56
Try this.  Go to admin plugin settings and click save.

**Comment by drnasin** [comment] 2019-02-12 11:00
@rhukster thank you. it works! We should label this somehow so people know the fix. I already had a call today from a customer complaining that not all parent pages are shown.

**Comment by rhukster** [comment] 2019-02-12 11:03
I’m assuming you are in 1.8 version of admin?

**Comment by drnasin** [comment] 2019-02-12 11:09
Yes. Would this PR be ok?

**Comment by drnasin** [comment] 2019-02-12 11:52
btw when you save admin page settings, parent will only work if show_modular is TRUE. Kind of confusing...

**Comment by drnasin** [comment] 2019-02-12 11:56
looking in the last commit seems like show_all_val == show_modular_val

```
 {% if show_modular_val == false %}
        {% set show_all_val = false %}
    {% endif %}
```

**Comment by rhukster** [comment] 2019-02-12 19:14
There's a better/simpler fix that I did in 1.9 but forgot to do in 1.8.  Basically just needed a default setting in the `admin.yaml` file.  I've done this now and released as 1.8.18.

**Comment by drnasin** [comment] 2019-02-13 16:09
I don't think the fix worked @rhukster. This now adds a new var show_modular on the root. Shouldn't it be inside pages as per `{% set show_modular_val = config.get('plugins.admin.pages.show_modular') %}`

Second problem. Parents are ONLY shown it show_modular = true …

**Comment by rhukster** [comment] 2019-02-13 17:48
DOH!!! Fixed the default setting, yes should of been under pages.

Now the default is 'true' so it will always be true unless you specifically set it to false.  That should be ok.

**Comment by drnasin** [comment] 2019-02-14 16:05
Ok, so just to be clear that this is wanted behavior. Setting pages.show_modular to false also hides (in the Parent text field) all pages that are not modular but have routable: false? Is this handled differently in 1.6 because this will be a hard bug to find for someone. Displaying normal pages as "parent" options should not imho depend on pages.show_modular var...

**Comment by mahagr** [comment] 2019-02-20 10:38
There are no behavioural changes in pages for Grav 1.6.

**Closed** 2021-02-11 17:14 UTC
Labels: question
