### ISSUE TITLE
Logs filled with Blueprints errors

### ISSUE THREAD

**Issue by Ribero** [getgrav/grav#3159] opened 2021-01-19 23:55 UTC
Grav v1.7.0 - Admin v1.10.0

The log file is full of this error: 

`[2021-01-19 23:48:26] grav.ERROR: Blueprint presentation/blueprints cannot be loaded: Directory name must not be empty. [] []`

Any idea of what cause this issue ?

**Comment by mahagr** [comment] 2021-01-20 08:45
This is likely the cause of your other issues. I don't know if it is caused by something which has changed in Grav or if you had a broken plugin installation before, but to me, it looks like a folder is either missing or something is being called too early.

@OleVik ?

**Comment by OleVik** [comment] 2021-01-20 11:28
Probably an inconsistency between blueprint-standards between 1.6 and 1.7, or any of the changes in 1.7's release candidates. Until 1.7 settles, assume any plugin can have incompatibilities. From the above, the management-interface in Admin may not work, but the plugin still should. I have yet to test the Presentation-plugin for 1.7's stable release.

**Comment by mahagr** [comment] 2021-01-20 12:10
@OleVik Let us know what it is, maybe it is a real bug in Grav 1.7.

**Comment by OleVik** [comment] 2021-01-20 20:45
I cannot reproduce this with a clean installation of Grav v1.7.1, Admin v1.10.1 and Presentation v4.0.1 (GPM-install). All blueprints appear to work as expected across the Presentation- and Slide-templates, as well as plugin-configuration, and rendering works on the front-end. No errors are logged as far as I can see.

@Ribero, please submit any additional information about your installation or what action leads to the entry to the log to the [Presentation](https://github.com/OleVik/grav-plugin-presentation/issues)-repository.

**Comment by mahagr** [comment] 2021-01-21 06:45
I am closing this issue. If it looks like a Grav bug, please be free to open a new issue. :)

**Closed by mahagr** 2021-01-21 06:45 UTC
Labels: evaluating
