### ISSUE TITLE
Multi language page with redirect_trailing_slash enabled

### ISSUE THREAD

**Issue by ossd** [getgrav/grav#2269] opened 2018-11-22 11:38 UTC
if redirect_trailing_slash is enabled and you are on a translated page and add a trailing slash, the redirect will redirect you to the default language version of this page

pull request #2268

**Comment by saxinte** [comment] 2018-11-23 16:42
Yes, I can confirm the problem is happening on Grav `v1.5.5`.

Also unnecessary redirects happens as well and cause SEO issues.

Here's what happen (tested with a new fresh build of Grav `v1.5.5` with enabled languages): 
https://www.mysite.com/de/foobar/
redirects to:
https://www.mysite.com/foobar
then redirects to:
https://www.mysite.com/en/foobar

The current language is lost in the redirects (`de` to `en`) and there's an unnecessary redirect as well.
It should be:
https://www.mysite.com/de/foobar/
redirects to:
https://www.mysite.com/de/foobar

This was not happening on Grav `v1.4.2` wich is the version I've updated from. But I needed it because of that fix: https://github.com/getgrav/grav/pull/2155

Thanks

**Comment by saxinte** [comment] 2019-01-16 12:58
@rhukster Problem has been fixed with https://github.com/getgrav/grav/pull/2155 and https://github.com/getgrav/grav/pull/2268 but introduced a tiny issue:

- https://www.mysite.com/contact?foo=bar OK
- https://www.mysite.com/contact/?foo=bar NOK (params been stripped out due to /)

can be tested on Grav v1.5.6 here:
- https://www.busuu.com/contact?foo=bar
- https://www.busuu.com/contact/?foo=bar

Thanks

**Comment by rhukster** [comment] 2019-01-17 00:06
I think i've fixed this, but in the 3.0 branch. I don't think this ever worked frankly as we never had any version that rebuilt the URL.

**Closed by rhukster** 2019-01-17 00:06 UTC
Labels: evaluating
