### ISSUE TITLE
Grav subpage issues : replicated fault (possibly flex object)

### ISSUE THREAD

**Issue by spamhater-grav** [getgrav/grav#3365] opened 2021-05-20 22:23 UTC
Had a couple of people identify an issue of strange folder numbering prefixing on the forum.

I now been able to identify a couple of linked issues 

If you create a numbered sub page / folder off the root under the admin panel, all is ok (due to the existing pages (01.home / 02.typography ) this look ok. 

If you then try and create a child to the subfolder / page, when the 'add page' or 'add folder' is displayed selecting the sub folder as a parent, it doesnt update correctly and will  still state / display "root"

If you then 'enable foldering numbering' and the save the page. It will display the page with a prefix of  999999.pagename , and this is displayed in the ordering.  If you then press the save button, it increments the folder name by 1 everytime.

It doesnt happen if there is a previous or manually created or renamed folder with the correct number (01) 
Any further depth down with also produce this issue. 

You see the result  in the screen recording, a few users have noticed and seem to be related to the recent flex-box updates.

All tested and issue is repeatable on a clean install of grav and users have queried the issue on the community forum.

https://user-images.githubusercontent.com/84087968/119056173-2629ce00-b9c2-11eb-90d2-bff4bb22e908.mp4

Many thanks

**Comment by pamtbaau** [comment] 2021-05-21 04:17
Is indeed reproducible. Happens since `Grav cor + Admin 1.7.8`

- `$ wget https://getgrav.org/download/core/grav-admin/1.7.8 .`
- `$ unzip 1.7.8 -d .`
- Login to site and go to `admin/pages/home`.
- Click `+Add`
- In modal form, enter name 'Child' and leave 'Parent page' as 'Home'
- Click `Continue`
- Click `Enable` for field 'Folder Numeric Prefix'
- Click `Save`
- Page will show `999999.Child` in field 'Sortable Pages'

**Comment by mahagr** [comment] 2021-05-26 07:56
The first issue is duplicate of #2136 (parent not changing).

**Closed** 2021-05-26 08:44 UTC
Labels: bug, fixed
