### ISSUE TITLE
"Trying to access array offset on value of type int" after php update from 7.3 to 7.4

### ISSUE THREAD

**Issue by ivanjimenez97** [getgrav/grav#3230] opened 2021-02-17 15:32 UTC
I was configuring a server, i installed apache, i installed there php 7.4, etc, and when i cloned the project i'm working i had bug.

Now every time i want to acces to the website The following message is displayed:

`An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type int").`
 
And with the following code: 

```
{% if not field.validate.ignore  %}
 
{% use 'forms/layouts/field-variables.html.twig' %}
{% block field_override_variables_before %}{% endblock %}
 
{% set field_name = (scope ~ field.name)|fieldName %}
{% set vertical = field.style == 'vertical' %}
 
"The message says this is the error" -----------> {% if not blueprints or (blueprints.schema.type(field.type)['input@'] ?? true) is same as(true) %}  <---------- "The message says this is the error"-----------------< 

  {% set default = field.default %}
    {% set toggleable = field.toggleable ?? false %}
    {% if toggleable %}
        {% set originalValue = originalValue is defined ? originalValue : value %}
        {% set toggleableChecked = originalValue is not null %}
    {% elseif field.overridable %}
        {% set toggleable = true %}
        {% set default = form.getDefaultValue(field.name) ?? default %}
        {% set toggleableChecked = value is not null and value != default %}
    {% endif %}
 
    {% set cookie_name = 'forms-' ~ form.name ~ '-' ~ field.name %}
    {% set value = value ?? get_cookie(cookie_name) %}
    {% set has_value = value is not same as(null) %}
    {% if not has_value %}
        {% set value = default %}
    {% endif %}
 
    {% if (field.yaml or field.validate.type == 'yaml') and value is iterable %}
        {% set value = value|toYaml %}
    {% endif %}
{% else %}
    {% set toggleable = false %}
{% endif %}
 
{# DEPRECATED: Needed by old form fields; remove when backwards compatibility breaks are allowed #}
{% set isDisabledToggleable = toggleable and not toggleableChecked %}
 
{% if toggleable %}
  {% set form_field_toggleable %}
    {% include 'forms/default/toggleable.html.twig' with {checked: toggleableChecked} %} 
```

- I did't edit nothing, i just downloaded the project, in my local i didn't have this. I checked what could be the problem, but in other issue i saw that could be the php version.

- Also I thought it could be problem of the server but when i updated the php version in my local from 7.3 to 7.4 i had the same problem. 

- I know that this bug could be solved if i install php 7.3 again, but the point here is we want to use a newer version.  

Anyone can help me? 
I'm not sure what to do in this case....

**Comment by mahagr** [comment] 2021-02-17 15:50
PHP 7.4 is more strict which causes issues where types have previously been mixed. Likely the issue is in the blueprint, but to know what is going on, you need to pass the full stack trace to figure out what happens.

**Comment by ivanjimenez97** [comment] 2021-02-17 16:16
@mahagr here is the stacktrace
```
Twig\Error\RuntimeError thrown with message "An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type int")."

Stacktrace:
#93 Twig\Error\RuntimeError in /var/www/enriqueramirez.test.com/docroot/user/plugins/form/templates/forms/default/field.html.twig:9
#92 Whoops\Exception\ErrorException in /var/www/enriqueramirez.test.com/docroot/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:569
#91 Grav\Common\Debugger:deprecatedErrorHandler in /var/www/enriqueramirez.test.com/docroot/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:569
#90 RocketTheme\Toolbox\Blueprints\BlueprintSchema:getFieldKey in /var/www/enriqueramirez.test.com/docroot/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:499
#89 RocketTheme\Toolbox\Blueprints\BlueprintSchema:parseFormField in /var/www/enriqueramirez.test.com/docroot/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:477
#88 RocketTheme\Toolbox\Blueprints\BlueprintSchema:parseFormFields in /var/www/enriqueramirez.test.com/docroot/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:222
#87 RocketTheme\Toolbox\Blueprints\BlueprintSchema:embed in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Data/Blueprint.php:345
#86 Grav\Common\Data\Blueprint:initInternals in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Data/Blueprint.php:314
#85 Grav\Common\Data\Blueprint:schema in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:700
#84 Twig\Template:getAttribute in /var/www/enriqueramirez.test.com/docroot/cache/twig/2f/2f84128012e44b06ef13cb2f64aefed4605932812fdcb96fae71b9f6e09ae418.php:56
#83 __TwigTemplate_a555eb9cf5a62ae0860c59880f99fd8825af3865059d749717832bb18a7f81ac:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#82 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#81 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/0e/0e896870756048d75209c15917834b3e57d09febd4fbdd947d713067dd3c4b23.php:34
#80 __TwigTemplate_921ee661ab120c104f2d83e7ccf6d1d4e67e7e5cc4c6ce5c0286382a0aa59155:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#79 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#78 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/38/38fe5b0ee7dae951afbf37dbc20f07d1e4e172ea5dfc1c84005804f396635bea.php:43
#77 __TwigTemplate_b4c5134be522a7881fa03212dbaa700a2b208983d2025d4b68a74faabf62697e:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#76 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#75 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/d3/d32851749e3cf0fa5b2738221fc18146b9622269d70ede9074b534be8767bb77.php:334
#74 __TwigTemplate_0ae472382928ca81bb77fa9aee684edfc065cea6bdc2fca144e7d8ba521896aa:block_field in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:214
#73 Twig\Template:displayBlock in /var/www/enriqueramirez.test.com/docroot/cache/twig/d3/d32851749e3cf0fa5b2738221fc18146b9622269d70ede9074b534be8767bb77.php:292
#72 __TwigTemplate_0ae472382928ca81bb77fa9aee684edfc065cea6bdc2fca144e7d8ba521896aa:block_inner_markup_fields in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:214
#71 Twig\Template:displayBlock in /var/www/enriqueramirez.test.com/docroot/cache/twig/d3/d32851749e3cf0fa5b2738221fc18146b9622269d70ede9074b534be8767bb77.php:184
#70 __TwigTemplate_0ae472382928ca81bb77fa9aee684edfc065cea6bdc2fca144e7d8ba521896aa:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#69 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#68 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/4d/4d04b4076303c540a42c076e6f0fd6f7bd3c7a5e0736573e49bbbe445af2232e.php:36
#67 __TwigTemplate_aff0e1bb7e19ecf576c81d29ca34ec5a5e8027123f7b85ff2d8c7c6a406455e3:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#66 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#65 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/e1/e1ac5d9becf26454651ffe4136259afe6f27e1d9d783236a672ef69d6c443f36.php:53
#64 __TwigTemplate_e5466e25b9b534d3ddd86bedb87717a6617f3a9c180c5e32521486bee8ae6760:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#63 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#62 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:432
#61 Twig\Template:render in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/TemplateWrapper.php:47
#60 Twig\TemplateWrapper:render in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Environment.php:384
#59 Twig\Environment:render in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Twig/Twig.php:296
#58 Grav\Common\Twig\Twig:processPage in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Page/Page.php:941
#57 Grav\Common\Page\Page:processTwig in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Page/Page.php:793
#56 Grav\Common\Page\Page:content in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:700
#55 Twig\Template:getAttribute in /var/www/enriqueramirez.test.com/docroot/cache/twig/ad/ad1b4f458b2143dba8c4b2ebaa35aa957c8d19b533edc726e4aae71b98b6f583.php:136
#54 __TwigTemplate_3c2676f14e37c7de1fc121e1a8a541c5f106745bbcd549c4d365973e1d61f3c9:block_content in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:214
#53 Twig\Template:displayBlock in /var/www/enriqueramirez.test.com/docroot/cache/twig/da/daf46227ee99a73e38b11c4bf1ff9cf7934f1243ed16fabd69d281eaf64f3ad2.php:249
#52 __TwigTemplate_f85d0811db4892a0e2bec247866307b0c240200f5bc2e1204b9ae26903ba11fa:block_body in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:214
#51 Twig\Template:displayBlock in /var/www/enriqueramirez.test.com/docroot/cache/twig/da/daf46227ee99a73e38b11c4bf1ff9cf7934f1243ed16fabd69d281eaf64f3ad2.php:84
#50 __TwigTemplate_f85d0811db4892a0e2bec247866307b0c240200f5bc2e1204b9ae26903ba11fa:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#49 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#48 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/cache/twig/ad/ad1b4f458b2143dba8c4b2ebaa35aa957c8d19b533edc726e4aae71b98b6f583.php:39
#47 __TwigTemplate_3c2676f14e37c7de1fc121e1a8a541c5f106745bbcd549c4d365973e1d61f3c9:doDisplay in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:453
#46 Twig\Template:displayWithErrorHandling in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:420
#45 Twig\Template:display in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Template.php:432
#44 Twig\Template:render in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/TemplateWrapper.php:47
#43 Twig\TemplateWrapper:render in /var/www/enriqueramirez.test.com/docroot/vendor/twig/twig/src/Environment.php:384
#42 Twig\Environment:render in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Twig/Twig.php:404
#41 Grav\Common\Twig\Twig:processSite in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Service/OutputServiceProvider.php:36
#40 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in /var/www/enriqueramirez.test.com/docroot/vendor/pimple/pimple/src/Pimple/Container.php:118
#39 Pimple\Container:offsetGet in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/RenderProcessor.php:39
#38 Grav\Common\Processors\RenderProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#37 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#36 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php:38
#35 Grav\Common\Processors\DebuggerAssetsProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#34 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#33 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/PagesProcessor.php:81
#32 Grav\Common\Processors\PagesProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#31 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#30 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/TwigProcessor.php:38
#29 Grav\Common\Processors\TwigProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#28 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#27 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/AssetsProcessor.php:39
#26 Grav\Common\Processors\AssetsProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#25 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#24 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/SchedulerProcessor.php:40
#23 Grav\Common\Processors\SchedulerProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#22 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#21 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/BackupsProcessor.php:39
#20 Grav\Common\Processors\BackupsProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#19 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#18 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/TasksProcessor.php:69
#17 Grav\Common\Processors\TasksProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#16 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#15 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/RequestProcessor.php:63
#14 Grav\Common\Processors\RequestProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#13 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#12 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/ThemesProcessor.php:38
#11 Grav\Common\Processors\ThemesProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#10 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#9 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/PluginsProcessor.php:39
#8 Grav\Common\Processors\PluginsProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#7 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#6 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/InitializeProcessor.php:128
#5 Grav\Common\Processors\InitializeProcessor:Grav\Common\Processors\{closure} in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Debugger.php:546
#4 Grav\Common\Debugger:profile in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Processors/InitializeProcessor.php:129
#3 Grav\Common\Processors\InitializeProcessor:process in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:50
#2 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php:62
#1 Grav\Framework\RequestHandler\RequestHandler:handle in /var/www/enriqueramirez.test.com/docroot/system/src/Grav/Common/Grav.php:282
#0 Grav\Common\Grav:process in /var/www/enriqueramirez.test.com/docroot/index.php:58

```

**Comment by mahagr** [comment] 2021-02-17 16:31
Thankyou. Fixed in the library.

**Closed** 2021-02-17 18:42 UTC
Labels: bug, fixed in repo
