### ISSUE TITLE
absolute_url filter return image tag

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1715] opened 2017-10-24 15:23 UTC
Hi !

I’m confused about usage of the `absolute_url` twig filter.

I can’t obtain an absolute url from this:

`url('theme://images/emails/header-bg.jpg')|absolute_url`
as it simply return the relative url

or this:

`media['theme://images/emails/header-bg.jpg']|absolute_url` is not working
as the absolute url is packed in an image tag:
`<img src="http://localhost:3000/user/themes/nature/images/emails/header-bg.jpg" />`

I've manage to get the desire result with a bunch of var combined but it would be better if `absolute_url` filter works normally.

That’s a strange behaviour that and `absolute_url` filter not return only the absolute url.

**Comment by rhukster** [comment] 2017-11-01 03:47
OK, maybe its not documented correctly because it is working as intended here:

```
'<img src="/some/path/to/image.jpg" />'|absolute_url = <img src="http://localhost/some/path/to/image.jpg" />
```

**Comment by jimblue** [comment] 2017-11-01 08:59
Ok @rhukster, thank you.

This return the same  result as absolute_url filter:

`{{ uri.base() ~ url('theme://images/emails/header-bg.jpg') }}`

**Comment by rhukster** [comment] 2017-11-02 20:54
Can we close???

**Comment by jimblue** [comment] 2017-11-02 21:07
Of course @rhukster you decide 😄 !

But I would said this filter is not perfectly clear as it's not returning an absolute_url in all case.

It would be probably be better if `absolute_url` could do the same as this:

`{{ uri.base() ~ url('theme://images/emails/header-bg.jpg') }}`

by simply using it like this:

`{{ url('theme://images/emails/header-bg.jpg')| absolute_url }}`

This is only my opinion, other people may like they way it's actually working, I can't tell.

**Comment by artemartemov** [comment] 2017-11-02 21:18
I also was having a bit of a struggle figuring that out - ended up going a different path but to me it didn't make too much sense that it would spit out `<img>` tags with the url.

**Comment by rhukster** [comment] 2017-11-02 21:19
I agree the naming is not the best and frankly quite misleading, but it takes a relative tag, and rewrites it with absolute url, and frankly we can't really change it now or risk issues where people are using it as it is.

So i'll close it.

**Closed by rhukster** 2017-11-02 21:19 UTC
Labels: investigating

**Comment by jimblue** [comment] 2017-11-02 21:20
Sure make sens for backward compatibility!
