### ISSUE TITLE
cannot connect to the GPM

### ISSUE THREAD

**Issue by rocandante** [getgrav/grav#505] opened 2015-12-06 02:24 UTC
Hi, I'm trying grav on my server. Apparently everything works fine but when I navigate in the admin repeatedly receive the message: cannot connect to the GPM. What does it mean? Am I missing something in the setup or configuration?

**Comment by w00fz** [comment] 2015-12-06 03:46
Check if you have openssl php extension enabled, that is required 

// Djamil Legato // From iPhone //

**Comment by superlou** [comment] 2015-12-08 01:17
I'm receive the same symptoms.  According to /admin/info, I have OpenSSL support enabled with library version "OpenSSL 1.0.1f 6 Jan 2014".  I started with the Notepad skeleton.

**Comment by rhukster** [comment] 2015-12-08 01:18
Do you get the same error from the command line `gpm` command as the admin? Do you have any firewall in place?  is your `bin/gpm` file set with executable permissions?

**Comment by superlou** [comment] 2015-12-08 01:25
From `ls -l`, my permissions are:

    -rwxrwxr-x 1 root www-data    1691 Dec  7 19:17 gpm

The command line `gpm` command works fine.  Running `bin/gpm list` does not give the message.  I don't believe I have a firewall in place.  I do have UFW firewall running with the following configuration:

```
To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
1622/tcp                   ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
1622/tcp (v6)              ALLOW       Anywhere (v6)
```

**Comment by w00fz** [comment] 2015-12-08 01:33
Can you try `bin/gpm index` command [not `list`] and see if you get the plugins/themes listed without errors?

**Comment by superlou** [comment] 2015-12-08 01:38
`bin/gpm index` runs without any warnings/errors.  Successfully lists plugins and themes then provides some messages on how to install.

**Comment by w00fz** [comment] 2015-12-08 01:41
Thanks, just making sure it's isolated to admin.
It's kind of strange because Admin shares the same methods that are used by `bin/gpm`.
Can you confirm you are running the same PHP on both web and cli ?

**Comment by superlou** [comment] 2015-12-08 01:47
Running `php -v` from the command line as root gives:

```
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

On the Configuration/Info page, the first heading is "PHP Version 5.5.9-1ubuntu4.14."  I agree it's pretty weird.  Are there any Admin interface actions that won't work if it really isn't able to access gpm?

**Comment by w00fz** [comment] 2015-12-08 02:03
The error **"cannot connect to the GPM"** is specific to accessing the `GPM::$grav` object that has all the data regarding Grav's updates. However there is no distinction between Admin and CLI, they both instantiate the same [`GPM` class](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/GPM.php).

If you go in `Plugins` and `Add` [`/admin/plugins/install`, do you get the whole list of plugins available for installation?

Also perhaps you can try editing the file [getgrav/grav/blob/develop/system/src/Grav/Common/GPM/GPM.php#L46](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/GPM.php#L46) and throw a proper error (ie, `var_dump($e); die;`), in case it's failing there.

**Comment by superlou** [comment] 2015-12-08 02:28
So, if I try to add a plugin (or theme), I get `ErrorException (E_ERROR)`: Call to a member function filter() on a non-object.  It's happening in plugins/admin/classes/admin.php lin 455:

```
    {
        $gpm = $this->gpm();
 
        if (!$gpm) {
            return;
        }
 
        return $local ? $gpm->getInstalledPlugins() : $gpm->getRepositoryPlugins()->filter(function (
            $package,
            $slug
```

Does that provide any insight, or should I try modifying GPM.php?

**Comment by w00fz** [comment] 2015-12-08 02:40
That error is not related, it's calling a method that is in Grav and hasn't been released yet, we need to get that out asap.
The fact that you can list the plugins for installation means you are accessing GPM, it is only failing to get the updates for Grav itself and not the Themes or Plugins.

Yes please, edit the `GPM.php` file and try throwing an error, there must be something in there that your server doesn't like.

**Comment by superlou** [comment] 2015-12-08 13:01
Sorry the hand-holding.  In that exception catch block, if I try `var_dump($e)`, I only get a white page back. I tried turning on errors with `ini_set('display_errors', 1); error_reporting(E_ALL);` but that doesn't seem to have any effect.  Is there somewhere in Grav that's hiding all PHP errors?

**Comment by superlou** [comment] 2015-12-09 01:12
I tried moving to the core+admin release, and I no longer receive the message.  It seems to be something to do with the Notepad skeleton.

**Comment by rhukster** [comment] 2015-12-09 21:41
That's pretty odd. I tried downloading the current notepad skeleton and tested GPM.  All worked fine.  I'll close this for now, please reopen if the issue reoccurs.

**Comment by lid3rs** [comment] 2015-12-15 09:58
Hello. I am receiving the same error message. I did a clean install on VPS. Then checked out my GIT repo and started receiving this message.

**Comment by flaviocopes** [comment] 2015-12-15 10:03
PHP has all curl and openssl installed? http://learn.getgrav.org/basics/requirements#php-requirements

**Comment by cravussin** [comment] 2015-12-23 13:47
Hi, I've got the same issue (cannot connect to GPM, exception on the filter() function when trying to add plugins) with latest Grav + Admin package (downloaded today). Windows 7 with XAMPP V3.2.2 installed

**Comment by flaviocopes** [comment] 2015-12-23 13:54
@cravussin the PHP requirements are matched?

**Comment by cravussin** [comment] 2015-12-23 13:58
Yes PHP 5.6.15

**Comment by flaviocopes** [comment] 2015-12-23 14:03
I mean `curl`, `openssl`, zip support http://learn.getgrav.org/basics/requirements#php-requirements

**Comment by cravussin** [comment] 2015-12-23 14:09
Yes all requirements are met. Actually, OpenSSL was missing at first, I activated it in php.ini then restarted the apache server.

**Comment by flaviocopes** [comment] 2015-12-23 14:17
Are plugins installed fine with the command-line utility? The problem is just in the admin, or also from there?

**Comment by cravussin** [comment] 2015-12-23 14:20
I'm not under Cygwin so I cannot use the CLI. Is there another way to install a plugin?

**Comment by flaviocopes** [comment] 2015-12-23 14:23
You can still download a plugin from http://getgrav.org/downloads/plugins, unzip and move the folder under `user/plugins`, e.g. `user/plugins/form/`

**Comment by cravussin** [comment] 2015-12-23 14:39
I suspect I might been having permission issues, reinstalling from scratch right now

**Comment by cravussin** [comment] 2015-12-23 14:46
Okay, so reinstalling XAMPP + Grav using only user permissions changed nothing, still the same issue.

I managed to install the instagram plugin manually.

**Comment by osriccaton** [comment] 2015-12-23 14:46
I had a similar issue. Setting the permissions right and adding the folder grav folder in ubuntu to www-data solved it for me.

**Comment by cravussin** [comment] 2015-12-23 14:51
I've installed XAMP as a user so everyhing in htdocs is writable.Strange issue really, it seems it's comming from the Admin plugin

**Comment by rhukster** [comment] 2015-12-23 15:33
You should try installing GitBash, then trying the command line tools:

```
> /path/to/php.exe bin/gpm index
```

From the root of your Grav install.  I doubt its GPM itself, or Grav Admin as many people have no problems.  99% sure it's a config/setup issue on your end.

**Comment by cravussin** [comment] 2015-12-23 16:24
I'll try again on my Mac later today and let you know.


Envoyé depuis mon iPhone

**Comment by cravussin** [comment] 2015-12-23 18:48
So it works flawlessly on my mac with MAMP 3.5. So it must be a Windows XAMPP vanilla configuration issue I suppose.

**Comment by rhukster** [comment] 2015-12-23 18:58
Most likely it's a missing PHP module (openssl, curl) or could be permissions, but that is less likely on windows.

**Comment by cravussin** [comment] 2015-12-24 06:37
I'll try with MAMP for Windiws today

**Comment by cravussin** [comment] 2015-12-24 09:07
Same issue with MAMP 3.5 for windows. There must be a problem between the win32 ports of apache / php and the Admin plugin.

**Comment by mrmlnc** [comment] 2015-12-24 09:33
Works fine on:
  
  * Windows 10 Pro (latest public build)
  * XAMPP v3.2.2 (PHP v5.6.15, default settings)
  * Grav Core v1.0.6 + Admin plugin (downloaded from the site)

**Comment by Corwin7** [comment] 2015-12-31 21:19
This problem occurred on a new Grav site I just set up. It was fixed with a simple `chown -R www-data:www-data /var/www/html/www.example.com`

**Comment by Endogen** [comment] 2016-01-01 11:21
I had the same issue on my CentOS server and the cause was that SELinux was enabled and it blocked the execution of gpm. On Cent you can disable SELinux with `sudo setenforce Permissive`. After that, i didn't get that error anymore. If someone is interested in reading about SELinux, go [here](https://wiki.centos.org/HowTos/SELinux)

**Comment by rhukster** [comment] 2016-01-05 00:39
We've added more informative errors that should help you with this going forward.

**Closed by rhukster** 2016-01-05 00:39 UTC
Labels: fixed in repo, question

**Comment by Gorcenski** [comment] 2016-01-10 05:05
I'm getting this error, too. Fresh Ubuntu 14.04 install, fresh install of Grav and the admin plugin. OpenSSL is enabled, curl is enabled, and permissions are configured. Any guidance on where to look for the source of the problem would be appreciated.

**Comment by rhukster** [comment] 2016-01-10 05:44
Is it possible you are behind a proxy?

**Comment by rhukster** [comment] 2016-01-10 06:21
The other thing to check is that curl and openssl are actually enabled in PHP for the CLI version: 

```
$ php -i | grep curl
$ php -i | grep openssl
```

I'm assuming your resting `bin/gpm` from the command line.  Best to try there first.  Also what exactly si the error you are getting?

**Comment by cravussin** [comment] 2016-01-10 09:58
I think you put the finger on the cause of my issue. I was having this problem at work where my station is behind a proxy. 

Is there a way to configure gym to go through a ntlmv2 authenticated proxy?


Envoyé depuis mon iPhone

**Comment by Gorcenski** [comment] 2016-01-10 20:38
@rhukster Solved it. It ended up being an ownership issue after all with the `www-data` user in Ubuntu server. I had run the permissions configuration script on the Troubleshooting page, but I still needed to perform a `chown -R...` after installing some plugins manually. Thanks again for your help!

**Comment by rhukster** [comment] 2016-01-10 20:45
No problem @Gorcenski , glad you got it sroted.

@cravussin check this comment out about how to set up some environment variables so Curl can use Proxy: https://github.com/getgrav/grav/issues/359#issuecomment-148369451

**Comment by cravussin** [comment] 2016-01-10 20:47
@rhukster cool thanks for the tip!

**Comment by happywky** [comment] 2016-03-26 01:54
I'm using xampp in mac to have a local test, The admin page pops up a bubble when:
turn on the openssl : internal sever error
turn off the openssl : Cannot connect to GPM 
//php -i | grep openssl

Configure Command =>  '/Library/Caches/com.apple.xbs/Binaries/apache_mod_php/apache_mod_php-101~18/Objects/php/configure'  '--prefix=/usr' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--sysconfdir=/private/etc' '--with-libdir=lib' '--enable-cli' '--with-iconv=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr' '--with-config-file-path=/etc' '--with-config-file-scan-dir=/Library/Server/Web/Config/php' '--with-libxml-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr' '--with-openssl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/local
openssl

**Comment by rhukster** [comment] 2016-03-26 01:58
You certainly do need **openssl** turned on.

if you get an internal server error, then there's probably something missing in your openssl setup.  The best way to find out what, is to look at your web server logs.

Quick question, is there a particular reason you are using xampp on a mac?  The usual suspects are MAMP or the built-in Apache with homebrew.  I've outlined detailed steps on using homebrew on a mac:  https://getgrav.org/blog/mac-os-x-apache-setup-multiple-php-versions

I strongly recommend this approach if you are tech-savvy, else MAMP is a solid and reliable way and 'just works'.

**Comment by arieedzig** [comment] 2016-08-27 03:33
Helo, after upgrading apache and using mod_ruid, the plugin and theme menu throw an error "Cannot connect to the GPM", I echo in Response.php and got error SSL peer certificate or SSH remote key was not OK, When I added this  CURLOPT_SSL_VERIFYHOST         => false,
            CURLOPT_SSL_VERIFYPEER         => false,
there were no more error. But I think this is not a good solution, because when I upgrade, those line will be overwritten. What should I do?

**Comment by rhukster** [comment] 2016-08-27 03:37
I think your ssl library is out of date. Our cert is perfectly valid.

Cheers!

--
Andy Miller
http://trilbymedia.com

**Comment by rhukster** [comment] 2016-08-27 15:09
@arieedzig I have actually updated our Cert with one from LetsEncrypt, let me know if your issue remains??

**Comment by arieedzig** [comment] 2016-08-29 14:03
Hi rhukster, still the same error.

**Comment by flaviocopes** [comment] 2016-08-29 14:11
You got the error only after you updated apache?

**Comment by arieedzig** [comment] 2016-08-30 13:27
Yes, before update, it was working.

**Comment by rhukster** [comment] 2016-08-30 14:00
can you disable this `mod_ruid`?  I know it's a suPHP alternative, but seems to be sort of old and unsupported?

**Comment by arieedzig** [comment] 2016-09-01 02:21
I activated mod_ruid to increase the security, so it will not possible for me to disable it.

**Comment by bennigraf** [comment] 2017-03-16 17:00
Hey,
for future reference: On my local dev machine I had the same issue with the openssl php extension being installed but still not being able to access gpm. The reason was there was no cert file configured to compare the gpm certificate against. I had to add something like 
`openssl.cafile=/opt/local/share/curl/curl-ca-bundle.crt`
to my php.ini to make it work (I installed openssl & curl via MacPorts).

**Comment by jodumont** [comment] 2018-01-31 03:12
@bennigraf 

I presume you add `openssl.cafile=/opt/local/share/curl/curl-ca-bundle.crt inside` :  `/etc/php7/conf.d/00_openssl.ini`

because `php -i | grep openssl` return me something like :

> openssl.cafile => no value => no value
> openssl.capath => no value => no value

But how you got this file : `/opt/local/share/curl/curl-ca-bundle.crt` because for me it is inexistent ?

**Comment by bennigraf** [comment] 2018-02-01 18:05
Hey @jodumont ,

Apparently that file was installed with the `curl-ca-bundle` package. (When you have MacPorts installed, do `port install curl-ca-bundle`...)

**Comment by nickydev** [comment] 2019-01-10 13:45
- [ ]
