### ISSUE TITLE
Markdown links to page media data files

### ISSUE THREAD

**Issue by rwstone** [getgrav/grav#452] opened 2015-11-18 18:23 UTC
I'm getting 404 errors when linking to pdf and txt files from Markdown.

When I include `[bid.pdf](bid.pdf)` in my Markdown, the generated slug-style html looks right:

`<a href="/grav/pdf-test/bid.pdf">bid.pdf</a>`

However, when I click through, I get a 404 Error.

**Comment by flaviocopes** [comment] 2015-11-18 18:33
Replicated, will work on a fix

**Comment by flaviocopes** [comment] 2015-11-18 20:40
Sorry, it's not a bug, it's a feature :)

Under system/config/system.yaml, you can see

```
pages:
  fallback_types: [png,jpg,jpeg,gif]        # Allowed types of files found if accessed via Page route
```

this defines the assed types that can be accessed through the page route.
Add 'pdf' to that list, in your own `user/config/system.yaml`

**Comment by rhukster** [comment] 2015-11-18 22:53
Ok this is properly fixed in develop for next release.  For now you can use the `pages.fallback_types` array and add `pdf` to it.  For next release this property is replaced by `media.allowed_fallback_types` that acts as a whitelist.  This should be left empty unless you are securing your site as it will now allow any valid media files by default.

**Closed by rhukster** 2015-11-18 22:53 UTC
Labels: bug

**Comment by rwstone** [comment] 2015-11-19 02:22
Thanks!
