### ISSUE TITLE
Page.find() fail when the URI is the same that home alias

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav#2398] opened 2019-03-06 18:27 UTC
Hello,
First, this is not a dupplicate of issue [#1843](https://github.com/getgrav/grav/issues/1843), but may be a correlated one.

edit : the present text has been edited, in order to fit the new situation.

While using `{% if page.find(item.URI) %}` in a macro to test the existence of the URI passed, ~~the condition _IF_ did nothing~~. With some more tests, it appeared that `{{ page.find(item.URI).url }}` wasn't returning the URI injected.

After a long discussion and debuggin on Discord, and a few personal testing, I discovered that :
- If a _page_ is defined in _system.yaml_ as a home alias for the project
- so, the function `page.find().url` with that page URI as a value, just returns the host url, **not the complete URI of the page**.

~~It could be a minorthing, if the `page.find()` existence check wasn't impacted too, this leading to possible disappointements for anyone not suspecting this function to fail.~~

### Steps to reproduce the behavior :

1. Create a page _/home/welcome_
2. In the default twig template, insert : 
```
<p>
	LINK TEST : <a href="{{ page.find('/home/welcome').url }}">test</a>
</p>
```
3. In _system.yaml_, edit the home alias like next : 
```
home:
  alias: /home/welcome
```
4. Access any page of your project in your browser, and check the generated link above in the codesource.

~~5. Additionally, perform a `{% if page.find('/home/welcome') %}` test with something to display in case of success, and not that it doesn't (the **existence check** fails).~~

I've just remade some tests, and it appears that the page.find() existence check just works fine. I may have confused some things in my many attempts.

**Comment by rhukster** [comment] 2019-03-10 18:50
I will investigate...

**Comment by mahagr** [comment] 2019-03-25 17:21
I think this works as intended as the route for that page is `/` so that one gets used. Grav `Page` object isn't aware of which path it was called for, it just has a single state.

In order to support something like this, the method should return a wrapper for the page instead of the page object itself. This is not supported right now, though it will be possible to do in Grav 1.6 after all plugins have been updated to accept `PageInterface` instead of `Page`.

**Comment by Romarain** [comment] 2019-03-25 17:41
At the opposite, I feel more logic to say that the route for the page **is the one composed of its sluggified path** (so it can allow what's highlighted in the bullet-list below), and that only the root path `/` is now "changed" to be the route of the aforementioned page (while not displayed in the URL bar).

But I know what any would say : _"no, that's the page's route `/home/welcome` wich is now rewrited to `/`, and not the root's route `/` wich is rewritten to `/home/welcome`"._ 

- But the facts are that both routes `/` and `/home/welcome` are reachable ! If you try to reach `/home/welcome`, GRAV will display that page, and won't redirect to `/`. And if I try to reach `/`, it will display the same page. 
- This offering the possibility to let the page accessible in the menu, and reachable with `/home/welcome`.

So, the assertion : 
> I think this works as intended as the route for that page is / so that one gets used.

Is not totally correct. It may be a paradoxal situation, and only a correct understanding of route processing under GRAV's core engine can explain why trying to retrieve the page's URI "fails" (meaning : it doesn't get the real sluggified path).

I don't know if you're right @mahagr (you may be), I just wanted to point that paradoxal aspect. ;)
I hope you will find a solution, despite it's a minor problem. For now, I think that just being aware of that URI flaw can help on finding why some template or plugin could fail.

**Comment by mahagr** [comment] 2019-03-25 17:46
I was just saying that every page is an object and there's just a single object for each page in the system. Root page also gets always assigned as `/` with an alias to the original location it was in. So in short, Grav isn't aware which way you accessed the page, it just knows that its default route is `/`. As of Grav 1.5, there's really no way to change that -- thus this behaviour cannot be supported.

**Comment by Romarain** [comment] 2019-03-25 17:47
Ok I understand `it just knows that its default route is /.` now ! Sorry for that misanderstanding.

**Comment by mahagr** [comment] 2019-03-25 17:53
Grav 1.6 can support this, though it would need all the Page plugins to be updated so that they would take the interface instead of the `Page` class. So it's kind of risky to add the behavior until people have had time to update their plugins (2.0?).

**Comment by mahagr** [comment] 2021-03-31 17:22
SEO does not like duplicate content, which is why this behavior is what is preferred. You find the page by using its name or alias, but the page should exist (or redirect) only to a single path.

Closing this as it is the direction we're moving to as it gets rid of SEO related issues.

**Closed by mahagr** 2021-03-31 17:22 UTC
Labels: question
