### ISSUE TITLE
Trying to install a plugin launch this error

### ISSUE THREAD

**Issue by JTorresConsulta** [getgrav/grav#3838] opened 2024-06-17 16:52 UTC
Trying to install the plugin: Shopping Cart  v1.2.3

`Dependency <cyan>form</cyan> is required in an older version than the one installed. This package must be updated. Please get in touch with its developer.`

My GRAV version:
v1.7.46 - Admin v1.10.46

**Comment by pamtbaau** [comment] 2024-06-22 22:18
Using same versions, I cannot reproduce the issue.

Tested:
- Installing using cmd `$ bin/gpm install shoppingcart`
- Installing from Admin plugins
- Installing from downloaded Zip

**Comment by JTorresConsulta** [comment] 2024-06-23 16:15
@pamtbaau 

I don´t have access to cmd, I was trying from the admin dashboard.

My server PHP version is 8.3.6 and Grav reports say "No errors found"
here is the screen capture of the error and reports.

![grav-server-reports](https://github.com/getgrav/grav/assets/22349981/92fd796c-660a-44cc-8538-0e9d9926ce90)

![grav-shop-error-installing](https://github.com/getgrav/grav/assets/22349981/2c2063e1-52e3-445d-9088-0fd59947f8f4)

**Comment by pamtbaau** [comment] 2024-06-23 16:51
Although I cannot reproduce the installation on a fresh install of Grav, the error you mention is known to the author. By the way, it  is not up to the Grav team to fix the issue.

See issues at the repo of the plugin:
- Januari 2024:https://github.com/leotiger/grav-plugin-shoppingcart/issues/8
- May 2019:  https://github.com/leotiger/grav-plugin-shoppingcart/issues/4

Unfortunately, the owner has not responded to both issues. The owner has recently been active on Discourse, you might create a new issue on his Githib repo, or contact him on https://discourse.getgrav.org.

**Comment by rhukster** [comment] 2024-10-23 10:59
Not a Grav issue, but rather a 3rd party plugin issue.. closing here.

**Closed by rhukster** 2024-10-23 10:59 UTC
