### ISSUE TITLE
Permissions of backups are wrong

### ISSUE THREAD

**Issue by AquaL1te** [getgrav/grav#2302] opened 2018-12-24 14:04 UTC
I just thought about restoring a backup when I found out the permissions aren't restored 1 on 1. In the backup zip file all dirs are 777 and all files are 666. This may be a limitation of zip files, which might not record file permissions.

Please provide a backup/restore functionality for true 1 on 1 restore capabilities.

**Comment by rhukster** [comment] 2019-01-01 08:17
Grav really doesn't set the permissions on the backup files explicitly, and zips do not inherently support permissions like tar files do. So most likely any issues you have are related to your setup and how you are performing the backups (ie, different permissions for PHP/webserver user compared to the user in your CLI).  I suggest using the CLI backup command.

Also backup has been rewritten from scratch in Grav 1.6, so might want to test with that.

**Comment by noisymime** [comment] 2020-01-10 05:19
Just to confirm, this is still an issue with Grav 1.6 (Specifically 1.6.11 in my case). A backup made through the web interface cannot be restored and used as the permissions differ from the original files, resulting on 403 errors on all pages

As a workaround, is it possible for Grav to not throw 403s when this occurs? The permissions on the restored files are more permissive than the originals, so there shouldn't actually be any access issues

**Comment by noisymime** [comment] 2020-01-10 05:25
And for anyone else stumbling across this and desperate to get a backup working, you can restore working permissions with the following two commands:
`find ./ -type d -exec chmod 775 {} \;`
`find ./ -type f -exec chmod 664 {} \;`

**Comment by mahagr** [comment] 2020-12-10 18:08
This is caused by a bad server configuration, closing.

**Closed by mahagr** 2020-12-10 18:08 UTC
Labels: question

**Comment by AquaL1te** [comment] 2020-12-11 08:50
> This is caused by a bad server configuration, closing.

Could you please elaborate on that? Because this issue still persists.

**Comment by mahagr** [comment] 2020-12-11 19:52
Permissions for all the files and folders use the permissions set in the HTTP server configuration. And how to do that depends on which server you use.
