### ISSUE TITLE
Link with different protocol

### ISSUE THREAD

**Issue by primeinc** [getgrav/grav#738] opened 2016-03-22 08:39 UTC
If I add a link like this on a non root page
```
**TS:** [ts.example.com](rdp://ts.example.com)
```
generates a link for rdp://ts.example.com/whatever/sub_folder/

I'd expect it to generate a link to: rdp://ts.example.com

Is this an issue with parsedown?

**Comment by flaviocopes** [comment] 2016-03-22 13:15
Confirmed, looks like an issue in Grav. Using protocols other than `http` or `https` get the page path appended.

**Comment by flaviocopes** [comment] 2016-03-22 13:17
For the time being, use a plain html URL: 

`**TS:** <a href="rdp://ts.example.com">ts.example.com </a>`

**Comment by flaviocopes** [comment] 2016-03-22 20:27
@rhukster was able to fix this by adding the protocol to ParsedownGravTrait::$special_protocols, is this the right way?

**Comment by flaviocopes** [comment] 2016-03-22 20:28
Or should it actually do the opposite? Whitelist `http/https` and leave the others unchanged?

**Comment by rhukster** [comment] 2016-03-23 04:00
It probably makes more sense to whitelist known correct protocols and attempt to retrieve the correct grav-related path, and leave all others as-is.

**Comment by rhukster** [comment] 2016-04-11 01:29
Fixed in develop branch

**Closed by rhukster** 2016-04-11 01:29 UTC
Labels: bug, recreated

**Comment by smz** [comment] 2016-04-11 01:51
:+1:  :smile:
