### ISSUE TITLE
Image orientation ?

### ISSUE THREAD

**Issue by symac** [getgrav/grav#544] opened 2015-12-20 22:47 UTC
Hello,
I have a picture taken with an iPad and directly uploaded to a page in Grav. It seems that Grav does not take into account the picture orientation. I have now renamed and resize the orientation of the picture, the picture is displaying correctly in my article but the thumbnail generated by Grav and used by pinpress theme on the front page is 180° rotated, any idea what is wrong? (I have cleared all the cache from Grav admin)

edit: my [example](http://geobib.fr/brickbrack/) with the last post (Christmas theme ;)) displaying wrong .

**Comment by symac** [comment] 2015-12-21 10:25
Forgive me, this is working this morning from another PC, so there was some caching issue, but Grav admin (or is it Grav) is not handling correctly rotated picture uploaded to a page directly from the iPad. I don't know what to do with this issue but there definitely is an issue with rotated pictures handling.

**Comment by flaviocopes** [comment] 2015-12-21 10:48
The problem is, the image is not "correctly rotated". iOS devices do not actually rotate the image, but put the rotation information in the EXIF data of the image.

Grav does not currently handle EXIF data on images, so you need to first remove the EXIF (e.g. http://www.cnet.com/how-to/how-to-view-remove-exif-photo-data-on-your-ios-device/), rotate it in your PC with an image editor and then upload it to Grav.

I'm aware that also WordPress for example does not handle EXIF data on images, as I got this same issue. 
But of course this could be handled by Grav, I'm marking it as an enhancement.

**Comment by symac** [comment] 2015-12-21 11:22
Thanks @flaviocopes I am not a Wordpress user and am surprised that EXIF metadata are not handled correctly by this widespread tool (I am just discovering that you need to use a plugin to have that done!), but definitely yes, Grav could handle this :+1:

**Comment by flaviocopes** [comment] 2015-12-21 13:03
(I just mentioned it because I recall the same problem there) - working on it

**Closed** 2015-12-22 04:15 UTC
Labels: enhancement, in progress

**Comment by bradlis7** [comment] 2016-10-19 01:45
@rhukster I feel like this isn't working still. I'm manually rotating them for my needs, but if there was a way to do this automatically, that would be much better for me.

**Comment by flaviocopes** [comment] 2016-10-19 09:57
It's not, the PR merged was removed due to issues it introduced. 
PR https://github.com/getgrav/grav/pull/555 should fix this problem, still need merging.
