### ISSUE TITLE
1.7.19: 'bin/gpm index' empty list on PHP 7.4.11, throws exception on PHP 8.0.0

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3092] opened 2020-12-05 15:15 UTC
PHP 7.4.11

- Clean install: `composer create-project getgrav/grav ./`
Grav v1.6.30
- `bin/gpm index` --> correct list of plugins/themes
- Upgrade Grav: `bin/gpm selfupgrade`
Grav v1.7.0-rc.19
- `bin/gpm index` --> Plugins/themes are listed, but no info.
  ```
  PLUGINS [ 109 ]
  ------------------------------------------------------------------------
  | Count | Name         | Slug               | Version  | Installed     |
  ========================================================================
  | Array |
  | Array |
  ...etc.
  ```

PHP 8.0.0
- Clean install from zip
 Grav v1.7.0-rc.19
- `bin/gpm index`
```
GPM Releases Configuration: Testing

PLUGINS [ 337 ]
PHP Fatal error:  Uncaught TypeError: mb_strwidth(): Argument #1 ($string) must be of type string, array given in /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Helper/StringLength.php:36
Stack trace:
#0 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Helper/StringLength.php(36): mb_strwidth()
#1 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Helper/StringLength.php(64): League\CLImate\TerminalObject\Basic\Table->lengthWithoutTags()
#2 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Basic/Table.php(234): League\CLImate\TerminalObject\Basic\Table->pad()
#3 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Basic/Table.php(216): League\CLImate\TerminalObject\Basic\Table->buildCell()
#4 /path/to/grav-admin/system/src/Grav/Console/TerminalObjects/Table.php(23): League\CLImate\TerminalObject\Basic\Table->buildRow()
#5 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Router/BasicRouter.php(28): Grav\Console\TerminalObjects\Table->result()
#6 /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Router/Router.php(99): League\CLImate\TerminalObject\Router\BasicRouter->execute()
#7 /path/to/grav-admin/vendor/league/climate/src/CLImate.php(384): League\CLImate\TerminalObject\Router\Router->execute()
#8 /path/to/grav-admin/vendor/league/climate/src/CLImate.php(399): League\CLImate\CLImate->buildTerminalObject()
#9 /path/to/grav-admin/vendor/league/climate/src/CLImate.php(435): League\CLImate\CLImate->routeRemainingMethod()
#10 /path/to/grav-admin/system/src/Grav/Console/Gpm/IndexCommand.php(131): League\CLImate\CLImate->__call()
#11 /path/to/grav-admin/system/src/Grav/Console/ConsoleCommand.php(41): Grav\Console\Gpm\IndexCommand->serve()
#12 /path/to/grav-admin/vendor/symfony/console/Command/Command.php(255): Grav\Console\ConsoleCommand->execute()
#13 /path/to/grav-admin/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#14 /path/to/grav-admin/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#15 /path/to/grav-admin/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#16 /path/to/grav-admin/bin/gpm(79): Symfony\Component\Console\Application->run()
#17 {main}
  thrown in /path/to/grav-admin/vendor/league/climate/src/TerminalObject/Helper/StringLength.php on line 36
```

**Comment by rhukster** [comment] 2020-12-05 18:38
I can confirm that `index` is not displayed as intended.  It looks like something changed with CLImate library update.  It only seems to impact the 'visual' side of things, `install` and `update` worked fine for me.

**Comment by pamtbaau** [comment] 2020-12-05 18:53
Not sure what you mean by 'visual', but `$ bin/gpm info <package>` also works fine.

**Comment by rhukster** [comment] 2020-12-05 19:43
visual = only impacts the displaying of the package in the CLI, it's not an issue retrieving the data, just presenting.

**Comment by mahagr** [comment] 2020-12-07 10:58
Should be fixed now.

**Closed by mahagr** 2020-12-07 10:58 UTC
Labels: 1.7, bug

**Comment by pamtbaau** [comment] 2020-12-08 06:16
Test confirms issue has been resolved.
