### ISSUE TITLE
Disabling translation fallback does not work

### ISSUE THREAD

**Issue by arkanos** [getgrav/grav#2517] opened 2019-05-23 15:47 UTC
Disabling the option for translation fallback seem to not work in our instance of Grav 1.6.9.

For example, we have articles in English and Spanish.

When the article doesn't exist in spanish, the english ones are retrieved instead even when the translation fallback option is enabled.

**Comment by rhukster** [comment] 2019-05-23 21:30
Actually, that option is only for 'translations', ie, the language strings in translation YAML files:

https://learn.getgrav.org/16/content/multi-language#translation-support

I think what you want is the `pages_fallback_only: true` option (this is new and not documented yet).

**Comment by arkanos** [comment] 2019-05-24 11:27
Hi @rhukster,

First of all, thanks for the quick reply.

I have enabled such option in system.yaml but still I'm getting the default language.

If there's anything else I can try or share with you please let me know.

Thanks

**Comment by rhukster** [comment] 2019-05-26 08:49
can you send me a demo 'user' folder where this is happening?  I cannot replicate it.

**Comment by arkanos** [comment] 2019-06-13 10:15
Hi @rhukster,

The content of our pages is kind of critical to be posted on the internet. Is there an e-mail address or something where I can share the file with you?

Thanks

**Comment by rhukster** [comment] 2019-06-15 20:46
rhuk at getgrav dot org

**Comment by veiss-com** [comment] 2019-07-10 12:25
Hi!!

I'm having the same issue.

I have a GRAV 1.6.11 installation and with pages_fallback_only: true I still getting articles in english when the language is french for example, and viceversa.

Is there a way to get the content in a collection only in the current language?

**Comment by mahagr** [comment] 2019-07-11 07:41
Do not use pages_fallback_only, it is not meant to display default language, but all languages in the list before the current one. Default option does not really work either, it's not doing what it is supposed to.

There is a fix for this in Grav 1.7, which both changes the logic to get default language only, but also allows you to override fallback languages per language basis.

**Comment by veiss-com** [comment] 2019-07-15 09:59
Hi @mahagr, thanks for your reply

I just  upgraded to --> Grav v1.7.0-beta.4 - Admin v1.10.0-beta.4

I see the "Content Language Fallback" option in the admin but I still gettin pages in french if this page in not in english when the current language is english for example.

I'm doing something wrong??

**Comment by mahagr** [comment] 2019-07-15 11:51
You should use the default value for that setting; it's really meant for versioning, not for languages.

**Comment by veiss-com** [comment] 2019-07-15 12:24
Thanks @mahagr here is my current languages configuration from my system.yaml:
languages:
  supported:
    - fr
    - en
  include_default_lang: true
  pages_fallback_only: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
  include_default_lang_file_extension: true
  content_fallback:
    fr-fr: ''
    en-en: ''

Im still getting pages in french when the currrent language is english for example.
I am missing something?

Thanks.

**Comment by mahagr** [comment] 2019-07-15 12:46
Content fallback is wrong, the keys should match the supported list values.

**Comment by veiss-com** [comment] 2019-07-16 06:26
Thanks @mahagr, I tried this:
languages:
  supported:
    - fr
    - en
  include_default_lang: true
  pages_fallback_only: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
  include_default_lang_file_extension: true
  content_fallback:
    fr-fr: fr
    en-en: en

And a lot more of combinations and i still getting the same result, is the current language in english and for example a page is only in french that page still appears in a collection.

**Comment by mahagr** [comment] 2019-07-18 12:08
The issue is in here:
```yaml
  content_fallback:
    fr-fr: fr
    en-en: en
```
It should be:
```yaml
  content_fallback:
    fr: fr
    en: en
```

**Closed** 2020-01-03 05:10 UTC
Labels: 1.7, fixed in repo
