### ISSUE TITLE
Grav duplicates pages and causes fatal errors when saving the mainmenu #2070

### ISSUE THREAD

**Issue by withindale** [getgrav/grav#1606] opened 2017-08-10 16:37 UTC
I have cross-posted this issue https://github.com/gantry/gantry5/issues/2070. This related to the same error when saving the mainmenu in a Gantry 5 Grav Supra site.

Grav triplicates pages causing fatal errors when saving the mainmenu (see issue #2015). This bug needs to be fixed with haste to make Grav fit for purpose! Here is a screenshot of the rogue pages:

![image](https://user-images.githubusercontent.com/17011185/29181052-a2261876-7df1-11e7-94c5-7e7fcc7b26df.png)

Note the following pages have been duplicated twice:
01.technologies
02.control
03.standards
as
05.technologies
06.control
07.standards
and interspersed with other pages as
07.technologies
08.control
09.standards

Only the second group have default.md files.

Grav corrupted this directory yesterday when I was adding and reordering pages (in the advanced tab of the page editor) in another directory. I have not made any changes to it recently so Grav or is it Gantry seems to have created the problem.

I resolved the problem for now by reconstructing the directory. However the cause remains and it really ought to be removed.

How to reproduce the problem? Not sure exactly but I suspect adding, renaming and reordering pages outside of the menu editor will do it.

**Comment by rhukster** [comment] 2017-08-11 17:27
@mahagr being the G5 expert, please take a look at this :)

**Comment by mahagr** [comment] 2017-08-15 12:28
I'm not able to reproduce the issue. Is there a reliable way to reproduce this issue?

**Comment by mahagr** [comment] 2018-04-30 12:09
Should be fixed in latest Gantry CI build. There is an underlying issue in Grav, though, where you can say one thing in the folder name and then override that inside the page header. This makes it really hard to handle page moving/saving in admin.

CC @rhukster

**Closed by mahagr** 2018-04-30 12:09 UTC
Labels: duplicate
