### ISSUE TITLE
1.1.x branch fails to run/install on Windows running Nginx 1.11.1

### ISSUE THREAD

**Issue by absalomedia** [getgrav/grav#961] opened 2016-07-26 12:32 UTC
Upgrading from 1.0.10 to the 1.1.x branch breaks everything on Windows when running Nginx.

Specs: 
- Windows 10  64-bit
- [WT Server](https://wtserver.wtriple.com/) running Nginx 1.11.1,  PHP 5.6, Maria & Redis enabled.

Replicated [this crash](https://gist.github.com/absalomedia/e6699e7157a64338c37368b20e14d2fa) from Whoops both in a development branch of a client site & in a clean / vanilla install of Grav 1.1.1 (with Admin).

Steps to replicate:

- Download Grav 1.1.1
- Set up WT Server with virtual local host records for site - replicate Nginx settings from Grav webserver-configs directory into virtual host file.
- Try to view site. Crash occurs on Pages line 1069
 
Also did a sideload test:
- Run Grav 1.0.10
- Update Admin plugin to 1.1.2 and install rest of Grav 1.1.1 plugin stack including Markdown notices
- Site still works

Something core related seems to not place nicely with Windows and/or Nginx it seems

**Comment by rhukster** [comment] 2016-07-27 01:43
That line seems to relate to the PHP 'intl' package being loaded.  Can you try to disable it in your php.ini and see if that fixes it?  

It seems that logic was added to fix issues with accented characters - https://github.com/getgrav/grav/commit/e2453b891d16f3c6500fe9c48e4035934df006c7

I'll also check with @flaviocopes to see if that's working ok for him still.

**Comment by absalomedia** [comment] 2016-07-27 07:24
Disabling the PHP intl extension gets things back to a working state.

**Comment by flaviocopes** [comment] 2016-07-27 14:56
replicated with wtserver

**Comment by flaviocopes** [comment] 2016-07-27 15:25
Fixed by https://github.com/getgrav/grav/commit/74f6890ce813ba44d4d26377de17d9c1532a1086 - not sure _why_ the constructor call fails as I could not find any reference, and the locale was set correctly.  Could not even catch it with a try/catch. Can you try the latest develop and see if the problem is solved for you @absalomedia ?

**Closed by flaviocopes** 2016-07-27 15:25 UTC
Labels: bug, investigating, recreated

**Comment by MartinKavik** [comment] 2016-08-06 17:21
@flaviocopes: I can confirm that your fix is working (WTServer + Win 7 + PHP 7).

 I think the problem is return value of `setlocale(LC_COLLATE, 0)` - in my case, it is **C** (viz e.g. [https://blog.mover.io/2012/11/21/php-locale-and-basename/](https://blog.mover.io/2012/11/21/php-locale-and-basename/)).
So the *Collator*'s constructor gets that "C" as argument and throws an exception, because it doesn't know what to do with it, imho. Your fix is working, because *::create* only returns *null* without throwing exceptions.

I am new in Grav world - is there any config files, where is possible to set default locale? (I assume, that it won't be last issue with locales).
