### ISSUE TITLE
Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by luguenth** [getgrav/grav#3083] opened 2020-11-27 14:54 UTC
Hey there!
I did a fresh and clean install on my server. 
After saving new parameters (Name of Author and Page-Title), the site threw an Exception:
```
 Whoops \ Exception \ ErrorException (E_NOTICE)
Trying to access array offset on value of type int

Stack frames (48)
Whoops\Exception\ErrorException
…/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php553

```
(PHP 7.4)

It still worked though and save the new settings. Things were quite stable. Now I've activated another theme, and now the Site completely broke and I'm getting the Exception all the time.

It's just a notice though, but never the less...

**Comment by mahagr** [comment] 2020-12-01 11:18
It looks like a field key is wrong, it should be a string, not a number. Can you provide more information what did you install and what did you do after that?

**Comment by luguenth** [comment] 2020-12-01 11:41
I did install it via the zip package. I think it was version 1.6.7, but I've no Idea how to get the current version number.
Except of the things above I did nothing more I suppose. Maybe I did some editing on the Example fields. Not so sure any more unfortunately :(
After setting up a new Instance I've no troubles anymore...

**Comment by mahagr** [comment] 2020-12-11 08:37
It must have been a bad blueprint file, as you said you were editing some example fields. I will close this issue as I don't have enough information to reproduce it. If you get the error again, please be free to inform me what you did so I can look if I can at least provide a better error.

**Closed by mahagr** 2020-12-11 08:37 UTC
Labels: more info needed
