### ISSUE TITLE
Image operations do not work within Markdown Extra Tags

### ISSUE THREAD

**Issue by fmms** [getgrav/grav#764] opened 2016-04-03 11:58 UTC
Hi,
I have created the following page:
```

![Sample Image 1](bg.jpg?lightbox=1024&crop=100,100,600,600)

<div class="container">
  <div class="row">
    <div class="col-lg-4 col-sm-6 col-xs-12" markdown="1">
![Sample Image 2](bg.jpg?lightbox=1024&crop=100,100,600,600)
    </div>
  </div>
</div>
```
The first image is correclty beeing resized, the second is not.

regards

**Comment by rhukster** [comment] 2016-04-04 18:08
I believe this is already fixed in the develop branch.  The issue is if you use multiple operations on the same image.

Can you **test** with the current develop branch?  Will require a composer update for sure.

**Comment by fmms** [comment] 2016-04-04 21:24
Is there any way to tell grav to just update my site? I could copy my folder containing the complete grav installation and then run some command to update it. ;) I have ssh access to the box. Do I have to do a clean instal, or is there some trick? Is there some public grav installation from nightly builds with write access?

**Comment by rhukster** [comment] 2016-04-04 21:30
Best to not actually update your live site. If you are familar with Git, I would:

1.  clone the Grav repo
2. run `bin/grav install` to get the vendor dependencies
3. **copy your user folder** from your live site into this new test site.

If not familiar with Git/Cloning, I would download this zip: `https://github.com/getgrav/grav/archive/develop.zip`, extract it in to your webroot, then perform steps 2 and 3.

**Comment by rhukster** [comment] 2016-04-05 00:40
I recreated on my local and it's not fixed.

**Comment by rhukster** [comment] 2016-04-05 00:42
It seems to be related to markdown extra, and specifically when a markdown image with enhanced operations is inside an HTML block with `markdown=1`

**Comment by rhukster** [comment] 2016-04-05 03:30
BTW, lightbox needs both **width** and **height**.  eg:

```
![Ironcat](ironcat.jpg?lightbox=600,600&cropZoom=100,100)
```

**Closed** 2016-04-05 03:29 UTC
Labels: bug, in progress, recreated
