### ISSUE TITLE
Empty modular page content causes Allowed memory size exhausted

### ISSUE THREAD

**Issue by tremel** [getgrav/grav#2113] opened 2018-07-22 08:46 UTC
The problem arises integrating https://github.com/variar/grav-plugin-unitegallery in my twig templates of a theme inheriting from Quark. The pages are generated by converting an old TYPO3 site and have lots of galleries on part of the pages.

So I added an empty block named `galleries` to `partials/base.html.twig` and modified `default.html.twig` in this way:

    {% extends 'partials/base.html.twig' %}
    {% macro pageLinkName(text) %}{{ text|lower|replace({' ':'_'}) }}{% endmacro %}

    {% block content %}
        {{ page.content }}
    {% endblock %}

    {% block galleries %}
        <div class="galleries">
        {% for module in page.collection('galleries') if module.template == 'modular/gallery' %}
            <div id="{{ _self.pageLinkName(module.menu) }}"></div>
            {{ module.content }}
        {% endfor %}
        </div>
    {% endblock %}

`modular/gallery.html.twig` is

    {% set grid_size = theme_var('grid-size') %}
    {% set columns = page.header.class == 'small' ? 'col-3 col-md-4 col-sm-6' : 'col-4 col-md-6 col-sm-12'  %}

    {% set gallery_id = (page.header.unitegallery.gallery_id ?: page.slug|ltrim('_')) %}
    {% set gallery_theme = page.parent.header.unitegallery.gallery_theme ?: 'tiles' %}
    {% set gallery_options = { 'gallery_theme': gallery_theme } %}

    {{ page.content }}

    <div class="gallery-container {{ page.header.class }}">
      {{ unite_gallery(page.media.images, gallery_options|json_encode, gallery_id) }}
    </div>

The problem is in the `{{ module.content }}` call in `default.html.twig`: If the markdown of the modular gallery page is _not empty every thing works as expected_. If the markdown is empty, only with a frontmatter in the md file, nothing of the modular template is rendered and even the debugger does not show up on the displayed page. Any content, even a html comment in the gallery md makes it run, but blanks are not sufficient.

Error in apache logs was:

    [Sun Jul 22 09:59:00.787786 2018] [:error] [pid 3152] [client 84.57.9.254:4906] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/domains/saint-josse-europe.eu/grav/system/src/Grav/Common/Plugin.php on line 265
    [Sun Jul 22 09:59:00.788029 2018] [:error] [pid 3152] [client 84.57.9.254:4906] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /var/www/domains/saint-josse-europe.eu/grav/vendor/monolog/monolog/src/Monolog/Logger.php on line 416

After increasing memory to 256 MB still errors, but in other routines:

    [Sun Jul 22 10:06:23.521845 2018] [:error] [pid 3695] [client 84.57.9.254:5300] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/domains/saint-josse-europe.eu/grav/vendor/symfony/event-dispatcher/Event Dispatcher.php on line 184
    [Sun Jul 22 10:06:23.522013 2018] [:error] [pid 3695] [client 84.57.9.254:5300] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/domains/saint-josse-europe.eu/grav/vendor/filp/whoops/src/Whoops/Run.php 

It's not a gallery problem, I know how to handle them, and the problem is the same if I omit the gallery call and just render some dummy html.

There must be a infinite loop somehow. Is this from my twig structure or is it a bug?

Additional information: In the frontmatter of the containing page I have

    galleries:
      items: '@self.modular'
    unitegallery:
      gallery_theme: tiles

Grav 1.4.7

See also my unsuccessful [post in forum](https://discourse.getgrav.org/t/modular-page-part-does-not-render-when-content-empty/6936).

**Comment by rhukster** [comment] 2018-07-25 22:45
I'm trying with Quark theme and I can't reproduce this....

**Comment by tremel** [comment] 2018-07-26 05:48
I transferred the theme to a fresh grav-skeleton-blog-site and cannot reproduce too. I will compare the two instances deeper to find the problem and will report.

**Comment by tremel** [comment] 2018-07-26 08:52
`bin/gpm uninstall image-captions` solved the problem.

**Comment by rhukster** [comment] 2018-07-26 23:37
Weird as that bug was fixed in 1.0.2 of image-captions:  https://github.com/trilbymedia/grav-plugin-image-captions/blob/develop/CHANGELOG.md

**Comment by tremel** [comment] 2018-07-27 04:32
Sorry, I am not a php champion and have no debugging configuration on my server. But the error is reproducible: when I install the plugin, the rendering is stopped by the memory limit, after uninstall the page renders as expected.

**Comment by rhukster** [comment] 2018-07-27 04:55
@tremel what version of `image-captions` was installed for you?  Can you reproduce the issue on `grav-skeleton-blog-site` by installing `image-captions`? Because it's not doing it for me with that skeleton.

**Comment by tremel** [comment] 2018-07-27 05:47
@rhukster I tested also with a grav-skeleton-blog-site I set up only for this purpose and Image Captions [v1.0.2]. Error is reproducible in this instance. Please see [grav-skeleton-blog-site.zip](https://github.com/getgrav/grav/files/2234557/grav-skeleton-blog-site.zip) with the relevant parts of my site. Use path `/jkirchenkapellen/a-osterreich/bezau` for test request.

**Comment by rhukster** [comment] 2018-07-27 20:45
Ok, i can see your error.. looking at it now...

**Comment by rhukster** [comment] 2018-07-27 21:09
Phew, found the problem, and fixed in image-captions: https://github.com/trilbymedia/grav-plugin-image-captions/commit/80fa7cb931f306475e03920ef297899b488fe1cc

**Closed by rhukster** 2018-07-27 21:09 UTC
Labels: cannot replicate

**Comment by rhukster** [comment] 2018-07-27 21:10
Also image-captions 1.0.3 released, should show up soon...

**Comment by tremel** [comment] 2018-07-28 07:51
@rhukster Thank you, great work. :-)
I had a look at the start of `processFigures` and had this part in mind, but could not imagine that a simple terminating return was harmful. Did not want to give silly hints with levity, sorry.
