### ISSUE TITLE
Errors in Admin Page - Plugins

### ISSUE THREAD

**Issue by synchro7** [getgrav/grav#1044] opened 2016-09-14 13:24 UTC
I'm using local server "Xampp".
`Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 19."

Stacktrace:
#31 Twig_Error_Runtime in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:402
#30 RuntimeException in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\GPM\GPM.php:473
#29 Grav\Common\GPM\GPM:findPackage in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:604
#28 call_user_func_array in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:604
#27 Twig_Template:getAttribute in C:\xampp\htdocs\grav-admin\cache\twig\b6\b6a16b9e99993d5305205028e010e1f471b3dfa16d9791de3725566abe70287b.php:72
#26 __TwigTemplate_812dd152f02b4c4e995fb2a2e134fb73f18fa1fc2bdaa0c164751063205c25e5:doDisplay in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:387
#25 Twig_Template:displayWithErrorHandling in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:355
#24 Twig_Template:display in C:\xampp\htdocs\grav-admin\cache\twig\4d\4d52b4af49aed4b34218dfba0d4aacb0e49c5ec1836447acc79aafdc1f78bf2f.php:218
#23 __TwigTemplate_d45efbb2ecfd1b6d175e48517c93ba1d3d4dbe975bc59085cd8b1e31d7a923f9:block_content in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:167
#22 Twig_Template:displayBlock in C:\xampp\htdocs\grav-admin\cache\twig\bc\bcedad5a9d9c096c0555639fe81c8eae8ad587d56962c88e545ddb97fbb1e4cb.php:205
#21 __TwigTemplate_a7caedeb0e8f9004b2ff859f14111da968f804e03a9687e4b90ccc5a5f872af1:block_page in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:167
#20 Twig_Template:displayBlock in C:\xampp\htdocs\grav-admin\cache\twig\bc\bcedad5a9d9c096c0555639fe81c8eae8ad587d56962c88e545ddb97fbb1e4cb.php:158
#19 __TwigTemplate_a7caedeb0e8f9004b2ff859f14111da968f804e03a9687e4b90ccc5a5f872af1:block_body in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:167
#18 Twig_Template:displayBlock in C:\xampp\htdocs\grav-admin\cache\twig\bc\bcedad5a9d9c096c0555639fe81c8eae8ad587d56962c88e545ddb97fbb1e4cb.php:45
#17 __TwigTemplate_a7caedeb0e8f9004b2ff859f14111da968f804e03a9687e4b90ccc5a5f872af1:doDisplay in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:387
#16 Twig_Template:displayWithErrorHandling in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:355
#15 Twig_Template:display in C:\xampp\htdocs\grav-admin\cache\twig\4d\4d52b4af49aed4b34218dfba0d4aacb0e49c5ec1836447acc79aafdc1f78bf2f.php:63
#14 __TwigTemplate_d45efbb2ecfd1b6d175e48517c93ba1d3d4dbe975bc59085cd8b1e31d7a923f9:doDisplay in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:387
#13 Twig_Template:displayWithErrorHandling in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:355
#12 Twig_Template:display in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Template.php:366
#11 Twig_Template:render in C:\xampp\htdocs\grav-admin\vendor\twig\twig\lib\Twig\Environment.php:347
#10 Twig_Environment:render in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Twig\Twig.php:340
#9 Grav\Common\Twig\Twig:processSite in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Service\OutputServiceProvider.php:19
#8 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in C:\xampp\htdocs\grav-admin\vendor\pimple\pimple\src\Pimple\Container.php:113
#7 Pimple\Container:offsetGet in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Processors\RenderProcessor.php:17
#6 Grav\Common\Processors\RenderProcessor:process in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:121
#5 Grav\Common\Grav:Grav\Common\{closure} in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:396
#4 Grav\Common\Grav:Grav\Common\{closure} in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:372
#3 call_user_func_array in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:372
#2 Grav\Common\Grav:__call in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:122
#1 Grav\Common\Grav:measureTime in C:\xampp\htdocs\grav-admin\system\src\Grav\Common\Grav.php:122
#0 Grav\Common\Grav:process in C:\xampp\htdocs\grav-admin\index.php:45
`

**Comment by flaviocopes** [comment] 2016-09-14 15:43
Make sure you satisfy these requirements https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-the-gpm

**Comment by synchro7** [comment] 2016-09-14 16:28
I checked everything, but it's still not working.

**Comment by rhukster** [comment] 2016-09-14 18:45
1) This is an admin issue, in future open here: https://github.com/getgrav/grav-plugin-admin/issues

2) "GPM not reachable" - means what it says. Grav can't reach the GPM info on https://getgrav.org.  Do you have a proxy server? Do you have a restrictive firewall?  If not then, the `cannot-connect-to-gpm` documented flavio linked contains all the common issue we know of.  Are you **sure** OpenSSL is installed and you have restarted your webserver since enabling it?

**Comment by synchro7** [comment] 2016-09-14 19:31
As I know, I don't have a proxy server. I've tried to disable firewall. I've check that OpenSSL is enable. I've tried everything. Also I get red alert every time I load admin page say: `this.data.feed_data is undefined at Grav</d</<.value@http://localhost/grav-admin/user/plugins/admin/themes/grav/js/admin.min.js?58888ea7a7:4:25071
Grav</d</<.value/<@http://localhost/grav-admin/user/plugins/admin/themes/grav/js/admin.min.js?58888ea7a7:4:24275
Grav</</o/<@http://localhost/grav-admin/user/plugins/admin/themes/grav/js/admin.min.js?58888ea7a7:4:23322` and `Error while trying to download 'https://getgrav.org/blog.atom'`

**Comment by w00fz** [comment] 2016-09-14 21:26
Please make sure it is actually enabled because I know XAMPP doesn't enable openssl by default.
Edit the proper php.ini file (or all of them if you have multiple PHP versions) and make sure you have this line uncommented:

```
[PHP_OPENSSL]
extension=php_openssl.dll
```

**Comment by synchro7** [comment] 2016-09-15 10:19
![image](https://cloud.githubusercontent.com/assets/10264979/18546421/160410fa-7b68-11e6-8dce-67fb04ff4c36.png)

![image](https://cloud.githubusercontent.com/assets/10264979/18546434/26093bec-7b68-11e6-99ee-495f0a94ab2f.png)

I've checked in php.ini, it's enable.

**Comment by maximelebreton** [comment] 2016-09-16 15:51
same for me

**Comment by flaviocopes** [comment] 2016-09-16 15:56
Can you both try MAMP for Windows https://www.mamp.info/en/downloads/ and check if the issue persists? In case it's a matter of server configuration, if not it's something else.

**Comment by synchro7** [comment] 2016-09-16 17:51
I've tried MAMP, still not working.

**Comment by w00fz** [comment] 2016-09-16 17:58
Have a look at this issue starting from the point i link down https://github.com/getgrav/grav/issues/1008#issuecomment-243041651 . Maybe that'll help you.

Specifically I'm providing some commands that helped determine the issue seemed to be related to the hosting provider. I know you are working locally but it might give us some hints.

``` shell
$ curl -I https://getgrav.org/downloads/plugins.json
```

**Comment by synchro7** [comment] 2016-09-16 18:10
![image](https://cloud.githubusercontent.com/assets/10264979/18596480/82fb84c0-7c73-11e6-865f-15a5e2ecf689.png)

**Comment by w00fz** [comment] 2016-09-16 18:23
Ok I am confused. Question: is if you go in the Plugins section, are you able to check for updates or is it failing? Do you get the error only in the Dashboard?

**Comment by synchro7** [comment] 2016-09-16 18:26
Dashboard:
![image](https://cloud.githubusercontent.com/assets/10264979/18596878/9050752a-7c75-11e6-9487-0ecf694449ac.png)

Plugins and Themes:
![image](https://cloud.githubusercontent.com/assets/10264979/18596902/aa345d6c-7c75-11e6-9ce0-317467b83d71.png)

**Comment by w00fz** [comment] 2016-09-16 18:29
Thanks. And if you do `bin/gpm index -f` you get the same?

**Comment by synchro7** [comment] 2016-09-16 18:31
![image](https://cloud.githubusercontent.com/assets/10264979/18597074/6a895798-7c76-11e6-8500-16adda56b4c6.png)

**Comment by w00fz** [comment] 2016-09-16 18:33
Ok. Can you do me a favor and look in your `php.ini` if you have `allow_url_fopen`. If it's enabled, turn it off, if it's disabled, turn it on. Then try again and see if it makes any difference.

Sorry for all the directions I'm giving, I'm quite baffled and trying to understand what is causing the issue because from my point of view, it should work.

**Comment by synchro7** [comment] 2016-09-16 18:46
allow_url_fopen was enable, I turned it off, but nothing is changed.

Thanks,

**Comment by synchro7** [comment] 2016-09-16 18:56
btw, I've been using my apartment's WiFi, it's quite restrict. Could that be the problem? I have not tried using Grav with other any other connection though.

**Comment by w00fz** [comment] 2016-09-16 19:00
You should get at least a different message in the error, as it should be going through cURL. I wonder if it didn't trigger it.

Also, if you can reach https://getgrav.org/downloads/plugins.json directly from your browser, you shouldn't have any issue with Grav.

Alright I have one other thing to try. Try editing the `Response.php` class (https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/Response.php#L176-L185) and invert the order of the checks, so instead of `fopen` first and `curl` later, make it `curl` first.

```php
    private static function getAuto()
    {
        if (self::isCurlAvailable()) {
            return self::getCurl(func_get_args());
        }
        if (!ini_get('open_basedir') && self::isFopenAvailable()) {
            return self::getFopen(func_get_args());
        }
    }
```

Disclaimer: it is ALWAYS a bad idea to directly editing source files, this is for testing purposes only so for posterity, don't do this :)

**Comment by synchro7** [comment] 2016-09-16 19:28
I can reach https://getgrav.org/downloads/plugins.json. 

After I've tried editing `Response.php`. I got errors like this:
![image](https://cloud.githubusercontent.com/assets/10264979/18598586/bf4e23d8-7c7d-11e6-8d44-31d6773fa909.png)

And, all the same in Plugins section.

**Comment by w00fz** [comment] 2016-09-16 19:35
In that same `Response.php` file, after line 43 (https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/Response.php#L43), can you add `CURLOPT_SSL_VERIFYPEER => false`?

**Comment by w00fz** [comment] 2016-09-16 19:37
Btw we are getting somewhere! It looks like the issue is how your machine interprets the SSL certificate we have for getgrav.org.

I'm not quite sure why it fails to verify that, it's a totally valid certificate. 🤔

**Comment by synchro7** [comment] 2016-09-16 19:39
`CURLOPT_HEADER => false` this line is already there in the file.

**Comment by w00fz** [comment] 2016-09-16 19:40
You should keep that one and add the `CURLOPT_SSL_VERIFYPEER => false` after.

**Comment by synchro7** [comment] 2016-09-16 19:41
Oh sorry my bad. lol.

**Comment by synchro7** [comment] 2016-09-16 19:44
Good news! It's working now.
![image](https://cloud.githubusercontent.com/assets/10264979/18599059/90455f90-7c80-11e6-8b82-b8cfad3d073b.png)

**Comment by w00fz** [comment] 2016-09-16 19:48
Very interesting. I'm glad this works for you but at the same time I'm confused as to why it didn't in the first place 😄 

If you look at our [certificate analysis](https://www.ssllabs.com/ssltest/analyze.html?d=getgrav.org&hideResults=on) it is marked as grade A which makes it all weird as of why your machine was complaining about verifying the peer.

I think we will add a new system option to disable the peer (so you don't have to touch the source files manually) and a note in the docs at the troubleshooting section.

Thank you so much for bearing with me on this and helping out figuring out the problem. None of the team could reproduce this issue!

**Comment by synchro7** [comment] 2016-09-16 19:57
You're welcome, it's been my pleasure helping out.

Thank you too, I can now work on my class project. Thank you everyone 😀

**Comment by maximelebreton** [comment] 2016-09-17 17:41
Works for me too with response.php edits, thanks!

**Comment by rhukster** [comment] 2016-09-17 17:46
Thanks we'll get this sorted for the next Grav release!

**Comment by w00fz** [comment] 2016-09-17 21:48
@maximelebreton out of curiosity could your describe your setup? Windows/Linux, php version, apache/Nginx and if windows/mac what bundle if any.

Thanks.

**Comment by maximelebreton** [comment] 2016-09-17 23:03
Windows 10
Apache/2.4.18 (Win32) PHP/7.0.4
Local server with EasyPhp DevServer

![image](https://cloud.githubusercontent.com/assets/1072425/18611505/398f9696-7d3b-11e6-905a-6087e5433804.png)

**Comment by w00fz** [comment] 2016-09-19 16:28
I integrated a new set of options for GPM that will allow to nicely disable the verify peer. #1053 
This will be available in the next release.

Thanks.

**Closed by w00fz** 2016-09-19 16:28 UTC
Labels: fixed in repo

**Comment by jeffreyroshan** [comment] 2016-09-23 14:27
**response.php edit** worked for me too. Thanks!

**Comment by judhi** [comment] 2016-09-26 09:12
I am sad to report that I have similar case with Grav installed on VPS with CentOS 5.11.
As previously discussed in issue #1008, setting **verify_peer = false** did help showing the normal pages and some Admin pages. But when I clicked on Plugin or Themes, I got this error message:

> Server Error
> Sorry, something went terribly wrong!
> 
> 0 - An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 19.
> 
> For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

Note that I already edit **Response.php** and added CURLOPT_SSL_VERIFYPEER => false** below **CURLOPT_HEADER => false** (line 43).

and also on line 348 (347 on the original file), added:

        curl_setopt($rch, CURLOPT_HEADER, false);
        curl_setopt($rch, CURLOPT_SSL_VERIFYPEER, false);

I feel sad because I really like Grav but tired of all of this SSL incompatibility issues :)

**Comment by judhi** [comment] 2016-09-26 10:18
Update:

Out of curiosity I just commented out line 19 of user/plugins/admin/themes/grav/templates/partials/plugins-list.html.twig and **it works!**


        {#% set releaseDate = plugin.date ?: admin.gpm.findPackage(slug).date %#}

I've got similar error when clicking on Theme tab of Admin page

> Server Error
> Sorry, something went terribly wrong!
> 
> 0 - An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/themes-list.html.twig" at line 21.
> 
> For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

So, again I just commenting out the mentioned line in user/plugins/admin/themes/grav/templates/partials/themes-list.html.twig:

        {#% set releaseDate = theme.date ?: admin.gpm.findPackage(slug).date %#}


and **it works!**

Still not sure why and what I am missing here.

**Comment by gianlucasavini** [comment] 2016-10-27 06:13
My two cents, on MAMP/Mac, switching to PHP 7 solved the issue

**Comment by AVDW** [comment] 2016-11-14 15:40
I've been having the same issues on Azure with PHP 7 in IIS, I've tried all the edits to response.php, enabled and disabled settings everywhere but **the solution @judhi posted worked for me!** Thanks @judhi !

**Comment by flaviocopes** [comment] 2016-11-15 09:39
Removing that line works because eliminates the connection to the GPM, but I guess installing or updating any plugin/theme won't work.

**Comment by AVDW** [comment] 2016-11-15 14:11
@flaviocopes  you're right, installing and updating does not work once that line is removed. 
I ended up putting those lines back in, deleted the cache, restarted the server then ran the following from the [grav troubleshooting page](https://learn.getgrav.org/troubleshooting/permissions) through the built in CMD interface on Azure. Using anything else apparently doesn't actually change the permissions on the folders.
`find . -type f | xargs chmod 664`
`find ./bin -type f | xargs chmod 775`
`find . -type d | xargs chmod 775`
`find . -type d | xargs chmod +s`

After that everything was working. I also went back into the configuration and turned on Remote Verify Peer and Remote Fetch Method to auto.

**Comment by Unrealstro** [comment] 2017-07-09 13:15
I was experiencing the same problem today. @AVDW is correct. The grav documentation is correct. Run the commands he mentions in the Azure app service console or the KConsole. Restart the app service and no more errors. FYI...the commands only work at the wwwroot folder. Any higher up and you will get errors.
