### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by enovision** [getgrav/grav#1741] opened 2017-11-08 11:28 UTC
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **enovision/grav-frontend-edit-button**

This plugin adds an 'edit this page' button on the frontend pages when logged in with a user account with admin rights. After clicking the button it will open the Admin Dashboard in another tab in your browser where you can start editing the page. Makes editing so much easier.

**Comment by lausek** [comment] 2017-11-08 12:58
Duplicate of #1731

**Comment by enovision** [comment] 2017-11-08 14:19
Sorry, but I thought you missed it,.. or I did...

**Closed** 2017-11-09 02:11 UTC
