### ISSUE TITLE
OPcache warning crashing some GRAV installs with php 7.2

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#1961] opened 2018-04-02 12:30 UTC
Using Grav with Linode / Serverpilot and php 7.2 (only 7.2, not php 7.0 and 7.1) gives the following error:

> An exception has been thrown during the rendering of a template (“Zend OPcache API is restricted by “restrict_api” configuration directive”).

This error can be fixed as per Joseph's comment here: https://discourse.getgrav.org/t/again-zend-opcache-api-is-restricted-by-restrict-api-configuration-directive/4569/7

Suggest this edit should maybe be rolled into the next Grav update, as it appears fix a bug on some setups...

Add an '@' prefix on line 71 of this file
/vendor/twig/twig/lib/Twig/Cache/Filesystem.php

                  @opcache_invalidate($key, true);

**Comment by rhukster** [comment] 2018-04-03 00:07
Unfortunately, that's a Twig bug and is upstream.  We can't fix that directly as it needs to be fixed in twig repo.

**Closed** 2018-04-03 00:08 UTC
Labels: bug, upstream

**Comment by rhukster** [comment] 2018-04-09 22:05
@MattAppleton  OK, there is a **proper** fix, that I came across while trying to solve this on a serverpilot controlled digital ocean droplet:

The error is caused by a configuration in php.ini for opcache: http://php.net/manual/en/opcache.configuration.php

To resolve, simply edit this setting in your php.ini (or relevant configuration file) for opcache settings.  In my case I had an `/etc/php7.2-sp/conf.d/opcache.ini` file that contained:

```
opcache.restrict_api=1
```

I just changed this to:

```
opcache.restrict_api=
```

and restarted PHP FPM with: `sudo service php7.2-fpm-sp restart`

**Comment by MattAppleton** [comment] 2018-04-09 22:08
Good stuff, thanks! Was manually editing vendor twig file in Grav core before, not ideal :)
